multitheftauto/mtasa-resources

- [gameplay]/freeroam/fr_client.lua
Warp to players with hex codes in their name doesn't work when "removeHex" is set to true in the meta.
> [freeroam] Warp to player with hex code doesn't work

- [admin]/admin2/meta.xml
Fixes ```ERROR: Couldn't find script server/admin_acl.lua for resource admin2```
> [admin2] Fixing path to server/admin_ACL.lua in meta.xml

- [gameplay]/freeroam/vehicles.xml
After the brownstreak carriage got re-enabled and fixed (r5934) it never got added to freeroam vehicles list.
> Re-added brownstreak carriage to vehicles list

- [gameplay]/freeroam/fr_client.lua
This fixes the abuse possible on Freeroam, if you get in another players' vehicle and F1 > int, setting interior. It won't since you aren't the driver, but as the dimension is set before this check, it will blank out their view on the world as dimension is changed already.
This glitch solves that by adding a check, thus preventing the annoying misuse of the bug, where they make the world for the driver invisible.
> Fix glitch of setting others' dimension as passenger

- [admin]/admin2/client/main/admin_chat.lua
Also omit a couple of errors by commenting the non-existent aAdminDestroy and checking for table[player]
In 'admin' it was in the options tab, but for some reason it's removed, so I added checkbox to the chat tab and made a setting for it.
Could someone please explain to me why there are two admin resources? I get that admin2 is the new version but why are there features still being added to admin (and not even being added to admin2 as well) - I'm asking because if someone were to contribute, they would probably opt for admin2, as it's the newest version.
> [admin2] Add adminChatOutput option

- [gameplay]/realdriveby/driveby_client.lua
Because the weapon's defined shooting speeds weren't applied if the method to change a weapon during driveby was to directly set the weapon into wield slot, it ends up as an abusable glitch where you can get for example, Deagle to fire 7 rounds in around a second, this is disastrous seen the damage it does per shot.
> Fix for rapid shooting glitch with slowfiring weapons

- [managers]/mapmanager/mapmanager.js
To reproduce this make sure that all maps have a gamemode attribute in the info tag
in meta.xml (no maps with no gamemode set) then just click on the mapmanager in the
resourcebrowser
The error was: "Uncaught TypeError: Cannot read property 'style' of undefined"
> [mapmanager] Fix for otherMapsContainer not having a header label

- [gameplay]/freeroam/fr_client.lua
This fixes http://bugs.mtasa.com/view.php?id=9061 and lets it draw the world correctly after setting position from int.
> Fix for #9061 (warp from interiors in freeroam)

- [gameplay]/freeroam/fr_client.lua
- [gameplay]/freeroam/fr_server.lua
Improved patch to fit sbx320's recommendation:
'' We may want to move vehicle passangers into interior 0 as well and remove players from their vehicle if they're not the driver. ''
So now that's also done, plus you can warp yourself + vehicle & passengers straight to the main world from interiors if you drive the vehicle in an interior. Also fixed warping from interior into player's vehicles in main world directly, also won't create blank world anymore but render correctly
> [Freeroam] Addendum to fix for #9061

- [gameplay]/freeroam/fr_server.lua
This is a second remake of old PR: #20 due to repo mismatch. (other remake failed due to some unintended commit linking)
Glitch was performed by switching to same weapon again, (/wp 26) (sawnoff) while in the very beginning of reload anim, cancelling it and evading it. If done quickly and fluently, switching between that /wp bind and constantly firing, will make you able to fire sawn-off rounds constantly and like an automatic, something disastrous seen the damage sawnoff shots do. That is now fixed and prevented with this, adding a forced reload on swapping sawnoff to interrupt the glitcher from progressing to constant firing & repeatedly cancelling reload.
New PR includes the quithandler ccw suggested for it to fit coding standards, and avoiding isElement (we have a proper quithandler …
> Fixed instant reload on sawnoff

- [admin]/admin/server/admin_server.lua
This is an easier way of doing the job and it doesnt trigger the "on[Client]PlayerSpawn" events.
> Patch for a better set Player skin

- [admin]/admin/server/admin_server.lua
This fixes several occasions on which the admin's nickname would be exposed and shown to the victim.
After this commit, the Anonymous admin tickbox really hides all occasions on which their name would not be hidden, as when the bug existed.
> Fix anonymous-admin option to really be anonymous

- [admin]/admin/client/gui/admin_inputbox.lua
- [admin]/admin/server/admin_server.lua
Implement possibility to manually add ban reason & player nick when banning a specific serial / IP of offline player through adminpanel ''Ban Serial'' or ''Ban IP'' button.
Previously, customly entering bans per serial / IP in adminpanel resulted in reason-less / nick-less bans that only contained the serial or IP in banlist.
This PR adds 2 fields to the ''Ban serial'' and ''Ban IP'' buttons to enter reason & nickname.
> Add GUI options on serial / IP ban: Reason & nick

- [admin]/admin/server/admin_server.lua
This commit fixes something I missed out on last PR #48; conform all bans to set banning admin to their accountname instead of nick.
It was meant to be the main feature of custom serial & IP ban, yet I missed it on these especially.
> Addendum to PR #48: fix inconsistency

- [admin]/admin/client/gui/admin_ban.lua
- [admin]/admin/client/gui/admin_inputbox.lua
- [admin]/admin/client/gui/admin_main.lua
- [admin]/admin/server/admin_server.lua
- [admin]/admin/server/admin_sync.lua
This commit introduces the feature of entering custom ban times for offline bans (Ban serial or Ban IP) where before this they could only be permanent until manually removed from banlist.
It also adds ''Unban time'' columns to adminpanel banlist (scroll in banlist properties + Ban details field) that calculates the ban times from Unix to date/time (format of timestamps banlist.xml uses) so both new and existing bans will get the unban date attached and visible.
Ignore the PR's commit numberings.
> Add unban date to bans and allow defining custom ban times for offline bans

- [editor]/edf/meta.xml
Doesn't break anything and allows resource developers to use OOP in resources with editor support
> Let the editor EDF scriptreader support OOP

- [gameplay]/freeroam/fr_client.lua
This patch blocks 2 anims from being used directly by /anim command rather than GUI, because they were abusable in combat with other players; the anim makes their ped go underground (under the world) so that they suddenly become invisible and unharmable by gunfire since within split second they'd be gone from sight (in reality just under the attacker's feet)
It could be used by command at the moment player almost dies with low HP, to prevent any attack from other player to succeed. It's unfair advantage.
> Fixed /anim abusable glitch

- [gameplay]/freeroam/fr_client.lua
- [gameplay]/freeroam/fr_server.lua
- [gameplay]/freeroam/meta.xml
_**Note from qaisjp: please squash merge if you decide to squash merge this**_
Players can use a method to load server and cause lag by using several binds **(or macros with many binds attached at once)** to mass-trigger functions that are serverside and many expensive, this was fixed by implementing anti-command spam that cancels execution in an early stage when triggered. ~~The basic anti command spam only limits certain commands to once in 2 secs~~ (and some funcs not, like repair, flip etc to not interfere with gameplay experience that much, as they can be spammed by players for legit reasons) +
- extended detection of deliberate spam, which only triggers at inhumane trigger speeds or mashing a bind, and then applies a command use ''ban'' preventing them to use any of the commands …
> Added freeroam anti-command spam to block crafted attack methods to cause lag

- [editor]/editor_main/client/main.lua
(disable CJ breathing and other related sounds in edit mode)
These sounds still works in test mode (thanks to resetMapInfo
somewhere).
https://forum.mtasa.com/topic/92093-bug-myth-breathing-sound/
> [editor] Stop creeping out mappers

- [admin]/admin/client/gui/admin_inputbox.lua
- [admin]/admin/client/gui/admin_message.lua
- [admin]/admin/client/gui/admin_messages.lua
- [admin]/admin/client/gui/admin_report.lua
- [admin]/admin/conf/reports.xml
- [admin]/admin/meta.xml
- [admin]/admin/server/admin_server.lua
- [admin]/admin/server/admin_serverprefs.lua
Added report category settings to reports.xml configuration. This will allow server owners to configure the report categories.
Added player report functionality. Each report category in reports.xml has an attribute called "isPlayerReport". If set to true, when reporting, the player will be asked to select the player that he wants to report. Admins will later be able to easily review the suspected player's information such as IP address, serial, MTA version, name and chat log.
Added Ban serial and Ban IP buttons in messages viewer. These buttons will only be enabled for report categories that have isPlayerReport set to true.
When clicked, a ban input box will appear with serial or IP automatically filled according to the report information. This will allow admins to save extra time, …
> Admin reporting system improvements

- [gameplay]/freeroam/fr_client.lua
- [gameplay]/freeroam/fr_server.lua
- [gameplay]/freeroam/util.lua
- Optimized server resource usage; Moved several functions to clientside, like TPing from map, warping, kniferestrictions, killing yourself, setting game speed
- Additional improvents, for example: improved weapon spawning code/preventing invalid commands from reaching server thus reducing load,
ensured playernames are consistent in other parts of Freeroam (like map), fixed long-existing bug where warping with bikes over long distance would
knock you off upon arrival and bounce you under/to the ground (this was tricky to fix due to https://bugs.mtasa.com/view.php?id=8522, it's any function with 'calmVehicle' in code)
- Added custom spawn position after death, if player gets killed now and before respawning opens map and clicks a position, he'll respawn there instead of at spawnpoint.
This …
> [Freeroam] several improvements #3

- [gameplay]/interiors/interiors_client.lua
Fixes two issues:
1) If you jump out vehicle, and later that vehicle touch marker, you will stuck in between interiors: https://youtu.be/rO0bQVbCDRQ
Fixed by simply replacing `isPedInVehicle` to `getPedOccupiedVehicle` (which return element also when player is leaving vehicle).
2) If you enter vehicle while you are being teleported, you will stuck: https://youtu.be/FzkNWI8olhg
Fixed by disallowing teleport when player is entering vehicle.
> [interiors] Fix player being stuck sometimes

- [gameplay]/freeroam/fr_client.lua
- [gameplay]/freeroam/fr_server.lua
- [gameplay]/freeroam/meta.xml
These newly implemented features are tickboxes in F1 allowing the player to eliminate some common bothering done by other players, such as ramming their vehicles (anti ram, aka vehicle ghostmode option), constantly knife instakilling them (from behind; stealthkill) now preventable with ''disable knifing'', and stopping other players from warping to them directly (using '''disable warp''). The concept for all of these features has been tested on the most popular freeroam server of right now, for more than a year, and they proved to be a very welcome addition for the average Freeroam player. It fits a gamemode like this perfectly.
Anyways, dialogue and discussion is still welcome in comments below.
> [freeroam] Added anti-bothering features (disable warp & knifing, ''anti ram'' vehicle ghostmode)

- [admin]/admin/admin_definitions.lua
- [admin]/admin/client/admin_client.lua
- [admin]/admin/client/gui/admin_main.lua
- [admin]/admin/client/gui/admin_messagebox.lua
- [admin]/admin/meta.xml
- [admin]/admin/server/admin_sync.lua
This PR adds a ban search feature to "Bans" tab, (by serial, ip, reason, name, or banning admin). The looping of bans has been optimized for performance, and a progress bar is there to indicate the search doesn't instantly complete.
Furthermore this PR bumps the version to 1.5.5 (which has lagged behind for a long time) and prevents a known gridlist sorting bug (temporary solution). It also notches down the "admin security level" to deal with debug spam in server console when commonly used scripts use setElementData intensively.
> Added ban search feature to "Bans" tab + misc

- [admin]/admin/conf/messages.xml
- [admin]/admin/server/admin_server.lua
When admins change something in ACL (add user, right, resource, new ACL, delete nodes, or rights) it will now log who did that and specify the exact right/element that was modified and in which way. Previously, a nondescriptive (hardcoded server) message just stated something had changed only, so for server owners, (malicious) actions could hardly be traced back to a specific admin.
Also added: more extensive logging for unbanning and banning offline players, for example it will now specify the serial/IP which gets unbanned and by who, instead of just stating a ban was removed.
> [admin] Added logging for ACL changes, unban etc

- [gameplay]/scoreboard/dxscoreboard_client.lua
- [gameplay]/scoreboard/dxscoreboard_countries.lua
- [gameplay]/scoreboard/dxscoreboard_exports.lua
- [gameplay]/scoreboard/meta.xml
Added option to show player's country in TAB playerlist, and implemented column image support to facilitate that.
It will draw both the flag and countrycode when enabled in meta.xml
> [scoreboard] Added countryflags to TAB

- [gameplay]/scoreboard/dxscoreboard_countries.lua
- [gameplay]/scoreboard/dxscoreboard_http.lua
`[gameplay]/scoreboard/dxscoreboard_countries.lua:18` and `[gameplay]/scoreboard/dxscoreboard_countries.lua:23` would throw server-side errors if the `admin` resource was not running.
```
ERROR: scoreboard\dxscoreboard_countries.lua:18: exports: Call to non-running server resource (admin) [string "?"]
ERROR: scoreboard\dxscoreboard_countries.lua:23: exports: Call to non-running server resource (admin) [string "?"]
```
Also removed an unnecessary comma from a table in `[gameplay]/scoreboard/dxscoreboard_http.lua:38`.
Bug report at https://bugs.mtasa.com/view.php?id=9835
> 0009835: [scoreboard] dxscoreboard_countries.lua throws two server-side errors if admin resource is not running

- [gameplay]/scoreboard/dxscoreboard_countries.lua
Faking the country flag can be done to prevent undesired recognition by players, which I realized is a downside of the flags feature. Admins may be located in a rare country (per the server's playerbase) or reconnect quickly under another nick and may want to remain anonymous.
PR is used to circumvent some GIT issue. However due to the unusual nature of this feature it will permit discussion of it.
> [scoreboard] add ability for server staff to spoof countryflag

- [gameplay]/freeroam/fr_client.lua
Fix the blackscreen occurring after using /sp when dead.
Also fixes error at line 1016 that occurs upon every start.
Closes #121
> [FIX] freeroam: Fix setpos blackscreen and error on start

- [gameplay]/freeroam/fr_client.lua
If the vehicle was removed by, eg, the admin panel, the buttons (flip, repair, etc.) were visible.
> Fix GUI after destroy vehicle

- [gameplay]/freeroam/fr_client.lua
This PR fixes GUI not being updated properly when a vehicle has been destroyed (passengers GUIs werent updated as it should)
Previous PR: https://github.com/multitheftauto/mtasa-resources/pull/125
- Luxy.c
> freeroam: Fix GUI after destroy vehicle (GUI wasnt updated for passengers)

- [admin]/admin2/server/admin_database.lua
Renames current conf\settings.db to admin.db. The reason for this change is for further implementations such as whowas, network tab, logging and maybe more :)
- Luxy.c
> admin2: renamed conf/settings.db to admin.db

- [gameplay]/realdriveby/driveby_client.lua
- [gameplay]/realdriveby/driveby_server.lua
- [gameplay]/realdriveby/exports_client.lua
- [gameplay]/realdriveby/exports_server.lua
- [gameplay]/realdriveby/meta.xml
This commit, once applied, enables toggling of the *realdriveby* feature for a specific player.
Fixes #137
- `bool isDrivebyEnabled ( player thePlayer )`
- `bool setDrivebyEnabled ( player thePlayer, bool enabled )`
- `bool isDrivebyEnabled ( )`
- `bool setDrivebyEnabled ( bool enabled [, bool syncToServer ] )`
- `driveby_enabled` (default value: `true`)
> Fix #137: Add exported functions and setting to toggle realdriveby on/off

- [admin]/admin2/client/main/admin_server.lua
- [admin]/admin2/server/admin_functions.lua
Fixes #104 
Use combobox instead of editbox for change weather. This PR also fix blend weather error.
> admin2: Finally fix for #104

- [gameplay]/freeroam/fr_client.lua
With this change the dxDrawText isn't just going to be static 1.3m above the player's position, this will follow the player's head.
Before: https://imgur.com/xSpGrdp
After: https://imgur.com/oCjwdsT
> Changed renderKnifingTag() getElementPosition to getPedBonePosition

- [admin]/admin2/client/main/admin_bans.lua
- [admin]/admin2/client/main/admin_options.lua
- [admin]/admin2/client/main/admin_resources.lua
- [admin]/admin2/client/main/backup!.lua
- [admin]/admin2/client/widgets/admin_acl.lua
- [admin]/admin2/client/widgets/admin_messages.lua
- [admin]/admin2/client/widgets/admin_spectator.lua
- [admin]/admin2/client/widgets/admin_stats.lua
Fix for https://github.com/multitheftauto/mtasa-resources/issues/171
admin2 still uses admin1's messageBox format.
Scripts now use messageBox correctly.
```aMessageBox()``` calls are now using the correct function ```messageBox()```.
Usage of coroutines instead of actions passed as arguments.
> admin2: fix messageBox usage

- [gameplay]/freeroam/fr_server.lua
The setting vehicles.maxidletime now accepts negative values. Any value below 0 will disable this functionality and the vehicles created by Freeroam will no longer be destroyed by idle time.
> vehicles.maxidletime can be disabled now

- [admin]/acpanel/c_gui_ac.lua
This PR adds a few missing SD entries (31-35) to the acpanel.
> Add missing SD entries to acpanel

- [admin]/admin2/client/main/admin_server.lua
- [admin]/admin2/server/admin_functions.lua
This PR changes the shutdown function of admin2 in two ways:
1. The reason input has been replaced with a confirmation dialog
2. The shutdown reason is generated by the server using the following format:
`Server shutdown as requested by resource admin2 (triggered by [player name])`
I think this is the best solution because:
1. In my experience, admins rarely (if ever) enter a shutdown reason 
2. This method ensures there is always a record of _who_ shut the server down (previously, there was no such record)
> admin2: new shutdown reason behaviour

- [admin]/admin/client/gui/admin_moddetails.lua
- [admin]/admin/server/admin_server.lua
- [admin]/admin/server/admin_sync.lua
This PR:
- Fixes #146 by adding a copy button to the player mod details view. Mod data is output in JSON format, for example:
```[
{
"gta3.img":[
{
"hash":1884619590,
"paddedLength":137216,
"id":20038,
"sha256":"DCE74CCF98956F4674BA483CF020D565DE312C53CD0CAB9FA0F66EAD3FDD25AE",
"paddedSha256":"D0EB8509152DE9A042F0883521DD8F331E0B202F4944AF6502B4A3F87507AAFD",
"name":"colt45.txd",
"md5":"0EA9CDB5CC5DEAD8DF16A50004E4EE7D",
"length":136616,
"paddedMd5":"F1333E03A4515523D0371EDDD915321C"
},
{
"originalSizeY":0.15000001,
"originalSizeX":0.44,
"paddedLength":49152,
"id":346,
"paddedMd5":"CE7B9114FC455CC3E9C7D0971F0F6924",
"sizeX":0.23,
"sizeY":0.039999999,
"paddedSha256":"C8EF9F8D1C64E67135F341CBCD2CF70399E6242B5B81CD4DB5F130E49203E8CF",
"originalSizeZ":0.20999999,
"name":"colt45.dff", …
```
> admin: improved player mod details view

- [gameplay]/freeroam/fr_server.lua
Spam prevention won't take effect if the player has ACL permissions to "command.kick" or "command.mute". Should help alleviate #119.
> freeroam: disable spam prevention for moderators

- [admin]/runcode/server.lua
Previously, runcode never checked for the right permissions leading to a security vulnerability.
This patch however fixes that by simply checking if the loggedin user has permissions to `command.srun`.
- LuX
> runcode: fix HTTP callback `httpRun` not checking for permissions

- [admin]/admin/conf/commands.xml
Command /setinterior should only accept string as 2nd argument because of interiors.xml. It's not like setElementInterior that only accepts integer.
> admin: fix setinterior command spec

- [editor]/editor_main/server/dumpxml.lua
Heyo!
I've recently gotten back into MTA and am already a big fan of the OOP-syntax - sadly when creating maps in the editor said OOP-syntax isn't working...
After looking around the files a bit I noticed that the `editor_test` map it generates (more specifically the `meta.xml` for it) doesn't include the `<oop>true</oop>` node.
This PR fixes that.
Seeing as the old methods are still working even if this is on I don't see it as a downside at all - quite the contrary, it's only beneficial to those that want to use that new syntax! :)
> editor: Add OOP support for editor_test map

- [editor]/editor_main/server/resourcehooks.lua
This is so it won't add several of the same node into the meta.xml file.
Sorry for not noticing this initially!
> editor: Clear oop node before saving

- [gameplay]/freeroam/fr_server.lua
- [gameplay]/freeroam/util_server.lua
For a long time it has been possible to avoid hex removal from a message in Freeroam. This PR fixes the problem.
The following message:
#00ff00color #00ff#ffffff00code
"color" would have it's hex code removed, and so would "code", but after removal of one hex code on word "code", it would join together as #00ff00code and thus the hex removal was avoided.
My apologies on description though. This PR makes sure that there can be no hex code present in player's message and fixes the earlier abuse problem.
> freeroam: fix exploit to get around hex code removal

- [admin]/runcode/client.lua
- [admin]/runcode/shared_util.lua
Makes it possible to watch variables easier.
Please review! (if you merge for me, please don't forget to squash)
**Screenshot**
**Usage**
Below are lines that you can run via `crun`.
```lua
-- Watch results of function
runcode.watch("cam", getCameraMatrix)
-- Watch results of runcode global
runcode.watch("global test", "kek")
kek = 9
-- Remove "global test"
runcode.watch("global test", nil)
```
**Enhancements for a future PR**
Might want to move the renders to below chat (pinned to left), rather than bottom right corner (pinned to right).
> runcode: add "watch variables" feature

- [admin]/runcode/server.lua
This PR resolves #180 by adding logging to commands executed by `/crun` & `httpRun`.
> runcode: add logging to `crun` and http

- [gameplay]/missiontimer/meta.xml
This PR fixes the following warning in missiontimer (used by a few of the default gamemodes):
`WARNING: [mtasa-resources]\[gameplay]\missiontimer\missiontimer_server.lua:29: <min_mta_version> section in the meta.xml is incorrect or missing (expected at least server 1.3.0-9.04570 because a send list is being used)`
> Fix min_mta_version warning in missiontimer

- [gameplay]/playercolors/playercolors.lua
When merged, this PR will fix a bug where playercolors default back to white when a map is unloaded by mapmanager. It also makes minor code quality improvements.
> playercolors: fix colors resetting when map is unloaded by mapmanager

- [editor]/editor_main/client/main.lua
Fixes #175 , the only solution that I could come up with for this issue that most likely won't break anything. (As I don't know in which cases it might be necessary to remove collisions for an elements representations)
It now iterates through the elements children and only disables the collisions if it has a representation that is not an object.
> Fix for #175

- [editor]/editor_main/client/main.lua
When dragging the representation the cursor could point at it which would result in the object moving away from itself.
For whatever reason I didn't come across this when  testing.
_And now I know why the collisions are  being disabled._
So here's a better fix that only disables the collisions when the element is being dragged.
> editor: replace 1729ceb (#219) with a better fix

- [gamemodes]/[race]/race/race_server.lua
Fixes #214 
btw i didn't find any clue why it's 6 seconds maybe a mistake?
i couldn't find any images to 4,5,6 in old versions, 
even the code it plays a sound 4 times instead of 6
`g_RaceStartCountdown:addClientHook(3, 'playSoundFrontEnd', 44)
g_RaceStartCountdown:addClientHook(2, 'playSoundFrontEnd', 44)
g_RaceStartCountdown:addClientHook(1, 'playSoundFrontEnd', 44)
g_RaceStartCountdown:addClientHook(0, 'playSoundFrontEnd', 45)`
> race: Change the start of countdown from 6 to 3

- [gameplay]/freeroam/fr_client.lua
Fix warning when time is set to freeze in fr_client.lua
> freeroam: Fix warning when time is set to freeze

- [gamemodes]/[race]/race/meta.xml
- [gamemodes]/[race]/race/modes/base.lua
- [gamemodes]/[race]/race/race_server.lua
Resolves https://github.com/multitheftauto/mtasa-resources/issues/187
Add `ghostalphalevel` setting to race to control ghost mode transparency.
> race: Add ghost mode transparency amount setting

- [managers]/votemanager/meta.xml
- [managers]/votemanager/votemanager_polls.lua
banPlayer provides a lot of banning options, none of which votemanager currently supports changing for its ban votes. This commit adds the following settings to the resource: 
1. voteban_banip true/false (default: true);
2. voteban_banusername true/false (default: false);
3. voteban_banserial true/false (default: false);
4. voteban_duration number in seconds (default: 3600)
Default values are the same as the default within banPlayer, except for duration, which is 1 hour instead of infinite. Note that voteban_enabled default remains false just as before.
The addition of the empty reason string when no reason is supplied via command is a workaround to avoid issues with lua's unpack() when unpacking tables containing nil entries. Here's an example: `local tab = {true,false,false,nil,5} …
> votemanager: added additional resource settings for ban votes

- .github/CODEOWNERS
- .github/CODE_OF_CONDUCT.md
- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/security_report.md
- .github/SECURITY.md
When merged this repo will add some miscellaneous repo files in the .github directory, including:
- CODE_OF_CONDUCT.md (direct copy from mtasa-blue)
- FUNDING.yml (direct copy from mtasa-blue)
- SECURITY.md (direct copy from mtasa-blue
It also updates the security_report template to provide updated guidance on reporting vulnerabilities.
> Add misc repo files

- [editor]/edf/meta.xml
This will fix the following warning:
`WARNING: edf <min_mta_version> section in the meta.xml is incorrect or missing (expected at least client 1.5.7-9.19626 because of 'setPedArmor')`
> edf: fix min_mta_version warning

- [editor]/editor_main/client/mapEditorScriptingExtension_c.lua
- [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
This pull request changes the table structure that transfers the lod models to the client to apply `engineSetModelLODDistance`, which can make loading much faster for resources with very large maps and with many LODS of the same ID.
Currently if the resource has the `useLODs` setting enabled in `meta.xml`, it loop all objects checking if that object has a valid LOD model (using a pre-written table inside the script), and if it does, it will add that model LOD within a table with `table.insert`.
The problem is: if the map file is very large and has many repeated objects with the same lod model, this value will be added several times within the table, and this can make the table very large, when in fact this lod model would only need to be stored once.
> editor: Change `usedLODModels` structure

- [editor]/edf/edf.lua
I've noticed that collision shapes are not created properly by editor resource and found the reason.
According to [mtawiki/Resource:Editor/EDF](https://wiki.multitheftauto.com/wiki/Resource:Editor/EDF) and file [editor/edf/datatypes.lua](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Beditor%5D/edf/datatypes.lua#L169) valid types of collision shapes are:
```
One of: "colcircle", "colcube", "colrectangle", "colsphere", "coltube"
```
But in [[editor]/edf/edf.lua](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Beditor%5D/edf/edf.lua#L93) there are checks for different strings - without the "col" in the beginning.
Also I've noticed that instead of ```createColCuboid``` a deprecated function ```createColCube``` is used.
Proposed PR fixes these and colshapes …
> editor: Fix creation of colshapes as children in custom EDFs

- [editor]/editor_main/server/freeroam.lua
hi, I always thought WARNING was a bit of an error message with red text and all so I replaced WARNING: string with INFO: and changed the text to appear as yellow instead of red.
this message appears when you start Editor resource while freeroam is running.
> editor: replaced WARNING with INFO

- [gameplay]/reload/reload_c.lua
This pull request rewrites part of the client-side code of the `reload` resource.
(We dont need to loop the `blockedTasks` table always we try to reload)
> refactoring reload_c.lua

- [gamemodes]/[race]/race/modes/base.lua
Hello,
While playing destruction derby maps with respawn of vehicles, rotation of vehicles had a little problem while respawning :
`WARNING: [gamemodes]/[race]/race/modes/base.lua:438: Bad argument @ 'setVehicleRotation' [Expected number at argument 4, got table]`
Here I suggest the way I solved it.
Have a nice evening.
> Race : Problem to restore rotation of vehicles - restorePlayer function - base.lua

- [gameplay]/reload/reload.lua
- [gameplay]/reload/reload_c.lua
Client:
- Replaced anonymous function with non anonymous, it's called reloadWeapon now.
- Renamed function **reloadWeapon** -> **reloadTimer** since it's called via timer.
- Due of that reloadWeapon it's now used as command handler/bind.
- triggerServerEvent uses localPlayer instead of resourceRoot.
Server:
- Localized event function.
- Added if check for client, according [to this wiki article.](https://wiki.multitheftauto.com/wiki/Script_security)
- Event's bound element changed to root, so it could also accept player as a source element.
> reload: few changes

- [admin]/ipb/client/gui.lua
This PR fixes a logic error, which caused the text in the `options` edit box to be used as filter param, and the `filter` edit box simply doesn't work.
> IPB: Fix filter editbox

- [admin]/admin/server/admin_server.lua
This PR changes permission checks to be done on the global `client` variable instead of on the event `source`. Since the event source is not guaranteed to be the player that triggered the event. (Think modified clients / injected Lua code)
Some detections are already in place to verify the `client` and `source` are equal, but with default configuration these are not enabled.  
Furthermore there really is no reason to use `source` over `client` in this case since `client` is always the correct client.
> Check the client for permission instead of the event source

- [gamemodes]/[race]/race/race_client.lua
- [gamemodes]/[race]/race/race_server.lua
fixes a bug related to respawnable pickups
> Pickup respawn fix

- [gameplay]/freeroam/fr_client.lua
When merged, this PR will fix the following error:
to reproduce it just use the command `addclothes` without arguments.
> freeroam: fix /addclothes error

- [gameplay]/freeroam/fr_client.lua
When merged, this PR will fix the following warning:
> freeroam: fix warning when using /color with negative number

- [editor]/editor_gui/client/save.lua
- [editor]/editor_gui/server/guiserverlink.lua
- [editor]/editor_main/client/saveloadtest_client.lua
- [editor]/editor_main/server/saveloadtest_server.lua
This pull request adds an option to change the config `mapResourceOrganizationalDirectory` using the save map dialog and fixes #287.
Before:
After:
> editor: fix #287 (organizational directory UI)

- [managers]/votemanager/votemanager_client.lua
This PR fixes warning (in the screenshot below) after cancelling a vote and choosing some option.
To reproduce it, just vote for any option, then cancel your vote _(press Backspace)_ 2 times.
> votemanager: fix warning after cancelling a vote and choosing some option

- [admin]/admin2/client/main/admin_players.lua
- [admin]/admin2/client/widgets/admin_interior.lua
- [admin]/admin2/client/widgets/admin_skin.lua
- [admin]/admin2/client/widgets/admin_vehicle.lua
- [admin]/admin2/client/widgets/admin_weapon.lua
> admin2: add filter to some lists

- [admin]/admin/client/gui/admin_spectator.lua
- [admin]/admin2/client/widgets/admin_spectator.lua
This PR adds to both admin and admin2, an option to enable/disable the camera collision when spectating any player using a little trick with processLineOfSight.
I am not sure if we should make it come activated by default, let me know your opinions.
screenshot:
video: (obviously, the 3d lines are only used for debugging purposes)
https://streamable.com/e/ehfljx
> admin & admin2: Add option to make camera collide while spectate

- [admin]/admin2/client/main/admin.lua
- [admin]/admin2/client/main/admin_chat.lua
- [admin]/admin2/client/main/admin_players.lua
- [admin]/admin2/client/main/admin_server.lua
As requested in #315, i've added these changes to admin2. (check #315's conversation for more details)
> admin2: add "hide sensitive data"

- [admin]/admin/client/gui/admin_screenshot.lua
- [admin]/admin/conf/ACL.xml
- [admin]/admin/server/admin_screenshot.lua
When merged, this PR will:
- Optimize bandwidth usage by using the _client_ global variable instead of passing the player by parameter.
- Fix permission checking by using an existing action name.
> admin: screenshot tweaks

- [gameplay]/speedometer/client.lua
When onClientElementModelChange is triggered it doesn't check that localPlayer is an occupant of source. So when you're inside a plane it sometimes showsSpeedo randomly (when the event is triggered elsewhere)
> speedometer: Check vehicle occupied by localPlayer

- [gameplay]/killmessages/utils/textlib.lua
Reverts multitheftauto/mtasa-resources#69 to resolve performance degradation noted in #331 - further improvements will follow in upcoming PR.
> Revert "Make killmessages support hex color" to resolve #331

- [admin]/admin/client/admin_client.lua
- [admin]/admin/meta.xml
This PR bumps `admin`s version number for the next release. As recommended by @iDannz1 in Discord, this will help advertise the fact that admin has had a number of improvements since the last release cycle and hopefully encourage admins to update.
> Bump admin version number for upcoming release

- [gameplay]/killmessages/scripts/client/c.killmessages.lua
This PR fixes the bug that duplicates the displayed lines but also ends up disabling ``freeroam`` suicide detection, so we need another method to detect it. ~~Anyway, I'm going to open an issue requesting this functionality back.~~
> killmessages: fix dup rows

- [editor]/editor_main/client/main.lua
This PR changes the `seeThroughStuff` / `shootThroughStuff` parameters of `processLineOfSight` so models with a certain material ID (eg. a fence ID 1413 with material ID 55) can be selected in the editor.
> editor: Make fences and similar objects selectable

- [admin]/admin/client/gui/admin_ban.lua
- [admin]/admin2/client/widgets/admin_ban.lua
This PR removes a warning that appears when clicking on the following label:
> admin/admin2: Fix bans warning

- [admin]/admin/client/admin_client.lua
- [admin]/admin/client/gui/admin_acl.lua
- [admin]/admin/client/gui/admin_interior.lua
- [admin]/admin/client/gui/admin_main.lua
- [admin]/admin/client/gui/admin_messagebox.lua
- [admin]/admin/client/gui/admin_permissions.lua
- [admin]/admin/client/gui/admin_settings.lua
- [admin]/admin/client/gui/admin_spectator.lua
- [admin]/admin/client/gui/admin_vehicle.lua
- [admin]/admin/client/gui/admin_warp.lua
- [admin]/admin/meta.xml
- [admin]/admin/server/admin_server.lua
- [admin]/admin/server/admin_sync.lua
This PR replaces deprecated functions, removes unused code, fixes calls to non-existing functions, etc...
I found them using [this](https://github.com/sumneko/vscode-lua), and maybe in the near future, i can send other PRs doing the same to other resources.
> admin: some tweaks

- [editor]/edf/edf.lua
- [editor]/editor_main/client/main.lua
Currently you can't remove interior world models in the editor.
In the below snippet from editor_main `interior` is always 0.
```lua
function onWorldObjectCreateOrDestroy ( )
if ( getElementType ( source ) == "removeWorldObject" ) then
local model = getElementData ( source, "model" )
local lodModel = getElementData ( source, "lodModel" )
local posX = getElementData ( source, "posX" )
local posY = getElementData ( source, "posY" )
local posZ = getElementData ( source, "posZ" )
local interior = getElementData ( source, "interior" )
local radius = getElementData ( source, "radius" )
if ( eventName == "onElementCreate" ) then
removeWorldModel ( model, radius, posX, posY, posZ, interior )
removeWorldModel ( lodModel, radius, posX, posY, posZ, interior )
else
restoreWorldModel ( model, radius, …
```
> editor: Make interior world models removable

- .github/workflows/linter.yml
Just fast Q&A to my PR
What is it? - https://en.wikipedia.org/wiki/Lint_(software)
Why is it need for **us**? - This repo is a library of examples for newbies and other scripters I think it must be pure and clear for all, even for our GC.
Is it need to merge now? - Not necessary. But if you want to see red crossmark on each commit about fixing the problems, you can. Anyway, you can set it as a "Draft".
How it looks? - https://github.com/Disinterpreter/mtasa-resources/runs/3697351842
Why are you ignore lot of marks in config? - Linter right now uses for common lua, and it hasn't our functions/variables/tables. We can fork it and change later.
Linter: https://github.com/mpeterv/luacheck
> Lua linter implementation

- [editor]/editor_main/gamemodestopper.lua
- Replaced bound element to predefined resourceRoot
- Used startedResource from parameters instead of method call getThisResource()
- Loop isn't called anymore when resource can't stop other resources (missing perms)
- Also it's no longer in it's scope (perm check)
- Replaced ipairs with better equivalent
- Improved readability
> editor_main: improve gamemodestopper

- [admin]/acpanel/c_gui_ac.lua
- [admin]/acpanel/c_gui_block_mods.lua
- [admin]/acpanel/c_gui_config.lua
- [admin]/acpanel/s_img_mod.lua
- [admin]/admin/client/gui/admin_main.lua
- [admin]/admin/client/gui/admin_skin.lua
- [admin]/admin/client/gui/admin_spectator.lua
- [admin]/admin/server/admin_ip2c.lua
- [admin]/admin/server/admin_server.lua
- [admin]/admin2/client/main/admin_acl.lua
- [admin]/admin2/client/widgets/admin_spectator.lua
- [admin]/admin2/server/admin_functions.lua
- [admin]/admin2/server/admin_proxy.lua
- [admin]/admin2/server/admin_storage.lua
- [admin]/admin2/shared/utils.lua
Just fixed the "previously defined" warnings in [admin] and seeing how to make PR. I'm unsure as to the need for "previously defined" warnings to be fixed, some seem less necessary to be fixed than others.
> Fix "previously defined" warnings in [admin]

- [gameplay]/deathpickups/deathpickups.lua
- [gameplay]/deathpickups/meta.xml
- Fixed pickup event handler (the code never passed through matchingDimension check because it was always nil).
- get methods are now called just on script init & when certain setting changes in resource.
- Improved readability & optimisation.
> deathpickups: some improvements

- [gameplay]/joinquit/joinquit.lua
- [gameplay]/joinquit/meta.xml
This PR introduces some quality of life improvements to the `joinquit` resource, as well as some basic enhancements:
- Moved the script server-side
- Added `*showColorCodes` setting which accepts a boolean value
- Added `*defaultColor` setting which accepts an RGB input, and controls what color to output the message text in
- Removed anonymous functions 
- Removed redundant support for alpha values which weren't present in hex code so I'm not sure why we used them
- Resource listens for settings changes
- Moved a few pieces of functionality into functions, namely `getDefaultColor` (which has a fallback now) and `getHexFriendlyNick` which makes the `outputChatBox` calls read nicer
> enhancement: joinquit settings support + code refactor

- [admin]/admin2/client/main/admin_options.lua
It was giving an error in admin2 so I took a look and saw that there was no `aOptionsTab.AdminChatLines` GUI. If I'm wrong correct me.
> Remove functions that parameters do not exist

- [gameplay]/rustlerbombs/client.lua
There was an unnecessary parameter "rustler" in the dropGliderBomb function which made the linter unhappy. As there's already a local variable defined to hold the rustler the player is in which is actually being used I have removed this parameter.
> rustlerbombs: Remove unnecessary parameter

- [editor]/editor_main/server/dumpxml.lua
Disabling it due of being unnecessary (no single OOP call was being used).
> editor_main: Disable OOP in meta.xml for scripting extensions

- [admin]/admin/client/gui/admin_maps.lua
extra check added to client/gui/admin_maps.lua line 69 to make exception if the source is the search bar editbox.
> Fix "No map selected!" message box when clicking search map editbox

- [editor]/edf/edf.lua
- [editor]/editor_main/client/main.lua
- [editor]/editor_main/server/saveloadtest_server.lua
f5fee65ca237d288dc6c77157c5717b5c7036148  Fixes error: [editor]\edf\edf.lua:623: Expected positive value, got negative.
54a3a87f52b151be5a86fbf4fb71a445895777a9 Fix editor break when try to edit static object created by script
Before this fix editor completely breaks after click on some object which was created by different script (-1 dimension)
Before:
After:
> editor_main: Fix various issues

- [editor]/freecam/freecam.lua
- [editor]/freecam/meta.xml
This PR makes the freecam (used mainly by map `editor`) ignore all mouse & key input when the MTA window is not focused, using the new https://wiki.multitheftauto.com/wiki/IsMTAWindowFocused function (since 1.5.9 r21313).
Meta.xml min_mta_version client updated.
This corrects the annoying behavior that you could reproduce by doing this:
1. play in windowed mode
2. open an application like calculator or another window, place it ontop of MTA window
3. pass your mouse on the MTA window, freecam would go crazy
> Fix freecam mouse & key input by ignoring it when MTA window not focused

- [gameplay]/scoreboard/dxscoreboard_client.lua
- [gameplay]/scoreboard/dxscoreboard_exports.lua
- [gameplay]/scoreboard/meta.xml
- Replaced client triggerServerEvent with onPlayerResourceStart.
- Changed event sources from root to lowest possible element.
- Use shared type for **dxscoreboard_shared.lua** in meta.xml, instead of twice defining it.
> scoreboard: Trigger events improvements

- [editor]/editor_main/meta.xml
- [editor]/editor_main/server/dumpxml.lua
This PR fixes version warning introduced in #385 
reported by @brenodanyel
> editor_main: Fix version warning

- [editor]/editor_main/client/main.lua
> editor: fixes delete button not restoring element. #412

- [admin]/admin2/server/admin_server.lua
- [admin]/ip2c/meta.xml
- [admin]/ip2c/server.lua
- [admin]/ip2c/shared.lua
Adds safety checks to arguments of `getCountryName( country )` and `getPlayerCountry ( player )`.
Also fixes `admin2` calling `getCountryName(aPlayers[player].country)` without checking if the country code is set. This would always trigger an error when playing on LAN as ip2c can't get any country from your local ip.
> ip2c: Add safety checks to exported function arguments

- [admin]/admin2/client/main/admin_players.lua
- [admin]/admin2/conf/messages.xml
- [admin]/admin2/server/admin_functions.lua
"Set nick" was previously missing any form of functionality beyond opening an input box. This pull request fixes that.
The input box will now correctly default to the current nick of the target player.
aFunction now has a "setnick" function associated in the player section that will change the target player's name as you would expect.
The messages.xml file was updated to include texts for the target player, the admin and the server log upon use. The color values were taken directly from admin1.
Additionally the two neighboring functions "sethealth" and "setarmour" received a minor fix, so that they now accept 0 as the lowest valid input and "sethealth" will no longer display an unintended message when the admin provides a non-number input. If undesired, the other commit can be …
> admin2: added missing set nick functionality

- [gameplay]/parachute/meta.xml
This fixes the following warning:
```
[2023-05-27 19:02:51] WARNING: [gameplay]\parachute\parachute.lua:18: <min_mta_version> section in the meta.xml is incorrect or missing (expected at least server 1.3.0-9.04570 because a send list is being used)
[2023-05-27 19:03:04] WARNING: [gameplay]\parachute\parachute.lua:32: <min_mta_version> section in the meta.xml is incorrect or missing (expected at least server 1.3.0-9.04570 because a send list is being used)
```
> parachute: Added missing min_mta_version for server to fix warning

- [managers]/votemanager/votemanager_polls.lua
Lint doesn't like [this line](https://github.com/multitheftauto/mtasa-resources/blame/b4119cca4665d63a3043f14c1624ce9c96700b96/%5Bmanagers%5D/votemanager/votemanager_polls.lua#L533)
`if exports.mapmanager:isGamemode(gamemode) and not exports.mapmanager:getRunningGamemode() == gamemode then`
It responds with:
> [managers]/votemanager/votemanager_polls.lua:533:51: Error prone negation: negation is executed before relational operator.
Hopefully it likes this new negationless line better.
`if exports.mapmanager:isGamemode(gamemode) and exports.mapmanager:getRunningGamemode() ~= gamemode then`
> votemanager: changed 'not x == y' to 'x ~= y' to appease lint

- [admin]/admin2/admin_definitions.lua
- [admin]/admin2/client/main/admin_players.lua
- [admin]/admin2/client/widgets/admin_permissions.lua
- [admin]/admin2/conf/messages.xml
- [admin]/admin2/meta.xml
- [admin]/admin2/server/admin_functions.lua
- [admin]/admin2/server/admin_sync.lua
admin2 currently has a non-functional "Give admin" button in the players tab. Not only is it not functional, but it's also a considerable downgrade from admin1's quick player permission management. This pull request brings admin1's permission widget over to admin2.
Since admin2 is structured slightly differently and I'm not very well-versed in working with either of the resources I'm not 100% sure about whether I adjusted for those differences correctly in the places I had to, but feedback from the developer discord so far has been positive. Particularly the data transmission between server and client and refreshing the displayed data might need checking, because I hardly know how it's expected to be used correctly.
> admin2: forward-ported permissions widget from admin1

- [admin]/admin2/client/main/admin_server.lua
- [admin]/admin2/server/admin_server.lua
This PR adding missing glitches and special world properties to the Server tab
> Added missing glitches and world properties

- [admin]/admin2/client/main/admin_acl.lua
- [admin]/admin2/server/admin_ACL.lua
This PR add content for "Users" sub tab in the "Rights" tab.
> admin2: Added content for "Users" sub-tab in the "Rights" tab

- [admin]/admin/admin_definitions.lua
- [admin]/admin/client/gui/admin_main.lua
- [admin]/admin/server/admin_server.lua
- [admin]/admin2/admin_definitions.lua
- [admin]/admin2/client/main/admin_chat.lua
- [admin]/admin2/server/admin_server.lua
Fixes #373 
Limit is 225 characters: the max chatbox message length, minus 7 for "ADMIN> ", minus 22 (max length for a player name), minus 2 (for ": ").
> Add limit to admin chat message length

- [gameplay]/defaultstats/defaultstats.lua
- changed resourceRoot to root in defaultstats.lua
- added conditions in applyStatsForEveryone to only apply stats when resource `type` is `gamemode` or `map`; or the resource itself.
> fix issue where defaultstats did not set player stats correctly (fixes #131)

- [gameplay]/speedometer/client.lua
This pull request adds a small piece of code to the speedometer resource that checks on start to see if the player is in this vehicle, and if so, displays the speedometer. Closes #477
> Display speedometer at resource start

- [gameplay]/playerblips/server/main.lua
The reason for this pull request is because the resource did not work the way I wanted it to. Only after I had a closer look at the code I realized that you can configure the playerblips resource in the `meta.xml`. Because I wanted the playerblips resource to take over the team colors that I have in my code, but that didn't happen. And since the server log said to activate the playercolors resource, I did it, but it didn't help. Only after I deactivated the playercolors resource and set "`use_team_colors`" to "`true`" did it work as expected. 
Anyway, the playercolors resource only makes sense if you want to have random player nametag colors, which makes no sense for teams, since teams can only have one color.
> playerblips: Fixed that the resource "playercolors" should be activated for teams

- [admin]/admin2/client/main/admin_acl.lua
- [admin]/admin2/server/admin_ACL.lua
This PR add content for "Resources" sub tab in the "Rights" tab.
This PR is a "continuation" of #445
> Added content for "Resources" sub-tab in the "Rights" tab

- [admin]/admin/server/admin_server.lua
- Moved the initialization of 'aLogMessages[type][action]' to after the definition of 'action'.
- Removed non-space invalid characters that were causing syntax errors.
> Fixed nil index error and removed invalid characters causing syntax errors

- [gameplay]/internetradio/client.lua
- [gameplay]/internetradio/server.lua
- Better naming for table with active radios
- Change event sources
- Save colors to variable
> internet radio: fix few things

- [gameplay]/internetradio/client.lua
This pull request refers to this issue (fixes #497) where the GUI window of the resource "internetradio" collides with the GUI window of the resource "helpmanager".
> Fixed that the GUI window of the resource "internetradio" collides with the GUI window of the resource "helpmanager"

- [admin]/admin/client/gui/admin_main.lua
This pull request ensures that the GUI settings window is no longer opened if you double-click on a resource name in the resource list and it has no settings. 
In this pull request https://github.com/multitheftauto/mtasa-resources/pull/490 with the change that the settings button should only be displayed if there are settings, I have not considered this.
> admin: Fixed that double clicking on a resource without setting opened the GUI settings window

- [admin]/admin2/server/admin_session.lua
There's a bug on admin2, start admin2, reconnect and login - 'p' bind isn't set
> admin2: fix bug onPlayerLogin 'p' bind not set

- [gamemodes]/[deathmatch]/deathmatch/client/hud.lua
- [gamemodes]/[deathmatch]/deathmatch/client/main.lua
- [gamemodes]/[deathmatch]/deathmatch/meta.xml
- [gamemodes]/[deathmatch]/deathmatch/server/main.lua
- [gamemodes]/[deathmatch]/deathmatch/server/player.lua
- [gamemodes]/[deathmatch]/deathmatch/server/round.lua
Use generic even/function names, use onPlayerResourceStart event.
> deathmatch: tiny cleanup

- [gameplay]/internetradio/config/CRadioConfig.lua
- [gameplay]/internetradio/handle_radio/CHandleRadio.lua
- [gameplay]/internetradio/handle_radio/ShHandleRadio.lua
- [gameplay]/internetradio/track_name/CRadioTrackName.lua
As in title, holding LALT (configurable in client-side config -> RADIO_SHOW_SPEAKER_OWNER_KEY) would display speaker owner
> internetradio: add ability to show speaker owner

- [admin]/security/NOTES.txt
- [admin]/security/events.lua
- [admin]/security/logging.lua
- [admin]/security/meta.xml
- [admin]/security/misc.lua
- [admin]/security/players.lua
As the notes say, this resource aims to be a barebone security foundation for server owners to enhance and adapt on for their personal gamemodes. As recent times showed, security needs to be highlighted more and this resource should give a base start point for developers to work on. It only covers the most basic events and logs them.
> basic security resource as a foundation

- [editor]/edf/properties_client.lua
This commit removes the property setter for object collisions as actually changing the collisions for objects in the editor mode makes them no longer selectable without High Sensivity Mode (e). processLineOfSight doesn't pickup collisionless objects.
This shouldn't really affect anything?
> Fixes #427

- [gameplay]/freeroam/fr_client.lua
resolves #529
Uses the max value of setMinuteDuration, so in theory 1 minute should just under 25 days.
Fixes the flickering, removes redundant timer and its 3 variables, in mtasa-resources freeroam weather is always static (correct me if I'm wrong), weather should be separate from freeze time.
Note: I can go back and use feature branch on my fork, this was purely accidental, my bad
> freeroam: fix freezetime flickering #529

- [gameplay]/freeroam/fr_client.lua
- [gameplay]/freeroam/meta.xml
This PR is a follow up to #530 to use the [new `setTimeFrozen` function](https://wiki.multitheftauto.com/wiki/SetTimeFrozen).
> freeroam: use new function setTimeFrozen

- [editor]/editor_gui/client/test.lua
Fixes #532, Currently the map editor shows the UI when collision patches are enabled during map testing, this caused by https://github.com/multitheftauto/mtasa-resources/blob/80d98fdc7daf7748756a7726b3261362ad8bdc9c/%5Beditor%5D/editor_gui/client/options_gui.lua#L127-L136
> editor: Fix UI appearing during map testing when "collision patches" enabled

- [editor]/editor_gui/client/test.lua
- [editor]/editor_main/server/saveloadtest_server.lua
Fixes: After testing a certain map with a gamemode (ex. race), you are unable to test the same map with the `<None>` option anymore.
Retains last testing gamemode upon reconnecting.
> [editor] Fix editor_gui test panel

- [editor]/editor_main/server/resourcehooks.lua
Fixes #538
This does not check for multiple files with different attributes (ex. scripts type that use both `client` and `server` instead of `shared`).
> [editor] Fix duplicate map meta entries resulting in editor suspending.

- [editor]/editor_main/client/rotation.lua
Make the "`Enable rotation patches`" work as a toggle between the current rotation behaviour and the old 1.5.9 rotation. 
`editor_gui` field might need a renaming.
Also fixes #537
> [editor] Toggleable rotation mechanic and improve threshold

- [editor]/move_keyboard/move_keyboard.lua
This PR fixes EDF rotation issue when setting the rotation manually or undoing an element, this could happen if you:
1. rotate > undo  > rotate after undoing
2. rotate > set rotation (F3) > rotate
This bug caused by a change in commit #400 
I used the race spawnpoint as an example
https://github.com/user-attachments/assets/8207c082-0cd2-4ed1-957a-93c9ef0904b6
> editor: Fix EDF custom elements rotation issues on undo/manual Adjustment

- [editor]/editor_main/client/main.lua
This elementData removal is being handled by `editor_gui` in `resumeGUI()`:
https://github.com/multitheftauto/mtasa-resources/blob/83e2c79cbd959aa54c55d4220a5b4d38747e8353/%5Beditor%5D/editor_gui/client/test.lua#L91-L97
I don't see any other reason for this to be in `editor_main`, unless I'm missing something..?
> [editor] Fix GUI not initializing on join after test map ending

- [gameplay]/internetradio/handle_radio/CHandleRadio.lua
Fix bugs caused by playing the sound in dimensions other than 0
- The sound created by playSound3D didn't move to the player's dimension, so the player could not hear it
- Track name wasn't visible in other dimensions
> internetradio: Fix playSound3D and track name showing in other dimensions

- [gamemodes]/[race]/race/edf/edf.lua
Duplicating a checkpoint with a nextid set would point that clone to the same checkpoint which resulted in multiple checkpoints pointing to another resulting in stray checkpoints.
When deleted checkpoints are in play and a new checkpoint was created, it would be automatically pointed to by said deleted checkpoint instead of an existing one, resulting in stray checkpoint sequences.
Fixed both. New checkpoints are now placed after the existing sequence as expected.
> Race edf: Fix automatic nextid assignment breaking

- [gameplay]/superman/client.lua
- [gameplay]/superman/meta.xml
- [gameplay]/superman/server.lua
- Use localPlayer instead of root in triggerServerEvent
- Remove unnecessary variable
- Add missing player in getPedControlState
- Disable cache for client.lua
> superman: Initial fixes

- [gameplay]/freeroam/fr_client.lua
Added onClientResourceStart and onClientResourceStop event handlers to listen on the root element.
When both the editor resource, and the race resource are active, it unbinds toggleMap from F2
When the editor resource is active, and you stop the race resource, it binds toggleMap back to F2.
Since the help menu in Race is only active when the editor is active, this should really be the only time it should either bind or unbind the toggleMap.
> Fix #535: Map key bind interferes with race editor help

- [gameplay]/freeroam/fr_client.lua
There is no point of putting 'elseif' on that spesific place, it causes problems with anti-ramming system since it actually blocks the setVehicleGhost(vehicle,hasDriverGhost(vehicle)), it should be 'end if' instead. That way when driver of the vehicle exits the vehicle, ghostmode vehicle can be back to it's normal state.
VIDEO of the bug: https://youtu.be/ZRFNxSeI1Eo
> freeroam: bugfix on fr_client.lua onExitVehicle function

- [gameplay]/voice_local/client.lua
- [gameplay]/voice_local/meta.xml
- [gameplay]/voice_local/server.lua
- [gameplay]/voice_local/shared.lua
This PR doesn't make any new major enhancements to the resource.
It fixes the scripts in terms of logic and security, and adds two important features:
- new meta.xml settings to configure the following:
- max voice distance - default 25 units
- show talking icon above player head - default true
- voice sound boost multiplier - default 6.0
Testing is recommended on a server with at least 1 other player.
> voice_local: fixes and improvements

- [gameplay]/freeroam/fr_client.lua
- [gameplay]/freeroam/fr_server.lua
- [gameplay]/freeroam/remote_player_call_validation_server.lua
This PR fixes a false positive in the `onPlayerTeleport` event caused by the use of `setElementPosition` on the client side, as well as resolving desync issues resulting from improper use of the function on the wrong execution side (issue: https://github.com/multitheftauto/mtasa-blue/issues/3993).
> freeroam: fix false positive issue in `onPlayerTeleport` event and desync.

- [editor]/edf/edf.lua
- [editor]/editor_gui/client/currentbrowser.lua
- [editor]/editor_main/server/dumpxml.lua
- [editor]/move_keyboard/move_keyboard.lua
Fixed a typo regarding default scale value
Fixed Indentation and shadowing of scale which is now currentScale
>  Fix typo and Lint: Indentation, shadowing

- [gamemodes]/[race]/race/modes/base.lua
Fixes #606.
Related to #595.
This PR also removes the unnecessary space that appeared after the change in PR #595 (`2 nd` -> `2nd`).
> race: Fix error in base.lua

- [gameplay]/parachute2/client.lua
I'll dig into how this resource works soon, so I can contribute to finishing it.
For now, this fixes the CI errors across PRs.
> parachute2: fix lint warnings

- [gamemodes]/[race]/race/edf/race.edf
Updated Race EDF to add autopimp and firewater settings and cylinder and arrow checkpoint types
> Update Race EDF

- [editor]/editor_gui/client/elementproperties.lua
This feature adds a new button that allows to copy both position (X, Y, Z) and rotation (rotX, rotY, rotZ) with a single click.
#643
> edf: Add Pullout button to copy position and rotation together

- [admin]/admin/client/gui/admin_main.lua
- [editor]/editor_main/client/elementcreation.lua
This is a minimal change.
Increase the FPS range label width from 0.1 to 0.12 to prevent the label text from being cut off.
> admin: Fix panel FPS range label width + Fixed lint error

- [gamemodes]/[race]/race/edf/race.edf
- [gamemodes]/[race]/race/meta.xml
- [gamemodes]/[race]/race/race_server.lua
- [gamemodes]/[race]/race/racemap.lua
This PR adds new settings that can be configured globally by the server or per map to control vehicle physics behavior. By default, they do not change the current behavior unless set in race or map settings. These settings were added to fix issues caused by multitheftauto/mtasa-blue#4243, which broke many custom maps and made them unfinishable. They allow server owners and mappers to bring back the old physics on specific maps by disabling the fix and setting the FPS those maps were designed for, without affecting other maps. The old behavior can also be enabled globally.
**New settings:**
- **`vehicle_physics_mode`**  
Controls physics behavior. `fixed` for FPS-independent physics, or `legacy` to restore the old behavior. Default is `fixed`.
- **`vehicle_physics_fps`**  
Sets the FPS …
> race: add new settings to control vehicle physics behavior

- [gamemodes]/[briefcaserace]/briefcaserace/client/br.client.driveby.lua
- [gamemodes]/[stealth]/stealth/noisebar.lua
- [gamemodes]/[stealth]/stealth/stealthmain_client.lua
- [web]/performancebrowser/performancebrowser_client.lua
> various: replace remaining getLocalPlayer function calls

- [editor]/editor_gui/client/options_gui.lua
Fix an issue where clicking on "enable sounds" or "enable bounding box" causes overlapping
Before:
After:
> editor_gui: Fix overlapping checkboxes
