multitheftauto/mtasa-resources

[gameplay]/freeroam/fr_client.lua
Fix for 0008837: [Freeroam] Removing clothes does not work
http://bugs.mtasa.com/view.php?id=8837
=> Fix for #8837

[gameplay]/freeroam/weapons.xml
For some reason the spraycan wasn't present yet
=> Added spraycan to freeroam weapons list

[admin]/admin/client/gui/admin_vehicle.lua, [admin]/admin/conf/messages.xml, [admin]/admin/server/admin_server.lua
Added an option to change a players vehicle license plate text from the
vehicle Customize menu.
=> Added license plate to Customize

README.md
A very trivial addition really, might be useful for whoever looks for the "Issues" tab and fails to find it.
=> Add a link to the bugtracker

[admin]/admin/client/gui/admin_maps.lua, [admin]/admin/server/admin_servermaps.lua
Not really anything too important, just a few error and warning messages
fixed.
Fixed the following errors:
- admin\server\admin_servermaps.lua:18: Bad argument @ 'call' [Expected
resource-data at argument 1, got boolean]
- admin\server\admin_servermaps.lua:19: bad argument #1 to 'ipairs'
(table expected, got boolean)
- admin\client\gui\admin_maps.lua:38: attempt to concatenate local 'map'
(a nil value)
- admin\client\gui\admin_maps.lua:39: attempt to concatenate local
'gamemode' (a nil value)
=> Maps tab bug fix

[gameplay]/missiontimer/missiontimer_client.lua, [gameplay]/missiontimer/missiontimer_draw.lua, [gameplay]/missiontimer/missiontimer_rpc.lua, [gameplay]/missiontimer/missiontimer_server.lua
=> [missiontimer] fix for debug error on non-ready clients

[admin]/admin/client/gui/admin_inputbox.lua
Fix something I missed out on @ last PR #50, making the GUI dropdown menu for bantime type look better.
=> Addendum to #50: fix GUI look on dropdown

[gamemodes]/[race]/race/race_server.lua
See [`[managers]/mapmanager/mapmanager_main.lua`:153](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Bmanagers%5D/mapmanager/mapmanager_main.lua#L153)
=> Race: Fix onGamemodeMapStop event

[admin]/admin/server/admin_server.lua
Log adminchat to server log. Server owners might want to know what is being discussed there.
=> Added adminchat logging

[gameplay]/killmessages/utils/textlib.lua
Hello, In that pull request will make killmessages more modern, It will support hex color by Default
Best regards
AboShanab.
=> Make killmessages support hex color

[gameplay]/realdriveby/driveby_client.lua, [gameplay]/realdriveby/driveby_server.lua, [gameplay]/realdriveby/meta.xml
Here are some realdriveby fixes.
This resource got some bugs which were really annoying.
I hope this time I did it right.
=> realdriveby fixes

[gameplay]/headshot/headshot.lua, [gameplay]/headshot/meta.xml
Added feature to blow off heads on headshot, and a setting to toggle it in meta.xml (enabled by default)
=> headshot: added support for blowing off heads

[gameplay]/freeroam/fr_client.lua, [gameplay]/freeroam/fr_server.lua, [gameplay]/freeroam/gui.lua, [gameplay]/freeroam/meta.xml, [gameplay]/freeroam/util.lua, [gameplay]/freeroam/util_server.lua
Most changes are to reduce load on server and thus improve performance,
- Improvements to anti-cmd spam timer and enabled it for all GUIs that send data to server to fight lag/spam macros
- Made some shared functions completely clientside (like flip vehicle, setting weather/time)
- Sanity checks for some functions/commands (arguments)
- Some other small improvements and more efficient design choices
=> [Freeroam] several improvements

[gameplay]/freeroam/fr_client.lua, [gameplay]/freeroam/fr_server.lua, [gameplay]/freeroam/meta.xml, [gameplay]/freeroam/util.lua, [gameplay]/freeroam/util_server.lua
This is the second PR containing commits aiming to improve Freeroam codebase quality with improvements & cleanup, and performance/effiency optimizations.
Together with previous PR (#78), memory and resources usage should be better.
- Added exception commands setting for antispam protection
- Improvements to vehicle spawning, including fix for space-containing vehicle names (like now, /cv Super GT works)
=> [Freeroam] several improvements #2

[editor]/editor_gui/client/browser/browser.lua, [editor]/editor_gui/client/browser/browserList.lua, [editor]/editor_gui/client/me_gui.lua
- Added a 'Favourites' category under 'All categories' in element browser.
- Right click on the gridlist to add/remove the highlighted element to favourites
- Favourites get saved to favourites.xml
- Also updated some deprecated functions
=> [editor] Added favourites

[editor]/edf/edf.edf, [editor]/edf/properties.lua, [editor]/edf/properties_client.lua, [editor]/editor_gui/client/browser/browser.lua, [editor]/editor_gui/client/browser/browserList.lua, [editor]/editor_gui/client/me_gui.lua, [editor]/editor_main/editor_main.edf
Added a new 'sirens' option that toggles sirens on vehicles that have them.
Also, since we are now able to change vehicle's number plates after it's created, I added this functionality (the plates now change as the property is changed).
=> [editor] Added 'sirens' option and fixed 'plate'

[admin]/admin2/client/main/admin_resources.lua, [admin]/admin2/server/admin_functions.lua, [admin]/admin2/server/admin_sync.lua
Fixed not being able to edit resource settings. I don't think there were any major edits but I'm not familiar with admin2 so let me know if something needs to be changed. Tested it and it works fine though.
Closes #96
=> [FIX] admin2: Fixed resource settings

Directory layout readme.txt
Change the header of `Directory layout readme.txt` slightly because of old language around 1.1 release.
=> Directory layout is no longer "new"

[admin]/admin2/client/main/admin_server.lua
=> Add more glitches and world properties into server tab.

[admin]/admin2/client/main/admin.lua, [admin]/admin2/client/main/admin_server.lua, [admin]/admin2/server/admin_server.lua
***Summary***
- Fixes #99, fixes #100, fixes #101, improves #104 
- During edit fields characters other than numbers has been disabled
- Enabled glitches, properties checkboxes and 'Set' buton for heat haze
- Added more properties to refresh function and added also glitches to refresh function
- Added validate if value of field is numer, empty field sets default value
- Added missing default value for field (eg. weather, fps)
- Unused code has been commented
=> Fix some issues

[admin]/admin/client/gui/admin_performance.lua
=> wrong path

[editor]/freecam/freecam.lua
Made it remotely triggerable.
Issue discovered by @MrPoper
Fix #165
=> Fix "doSetFreecamOption" remote triggering

[admin]/admin2/client/main/admin_players.lua
Fixes #152 
Now if we use DOWN or UP arrow key, informations like freeze,mute,ip,serial etc will be update/set
=> admin2: Fix #152

[gameplay]/freeroam/meta.xml
Specified on comments about using negative values on vehicles.maxidletime setting.
=> Added comments related to idle time

[admin]/admin2/client/admin_wrapper.lua, [admin]/admin2/client/main/admin_players.lua, [admin]/admin2/client/widgets/admin_warp.lua, [admin]/admin2/conf/messages.xml, [admin]/admin2/meta.xml, [admin]/admin2/server/admin_functions.lua, [admin]/admin2/server/admin_server.lua, [admin]/admin2/shared/utils.lua
I changed various things which can be seen by commit messages. I sadly wasnt able to remove that 1 commit so i just reverted it - if anyone knows how to remove those entirely, please do so.
// cc: @qaisjp
=> admin2: Various changes & additions

[admin]/admin/conf/interiors.xml, [admin]/admin2/conf/interiors.xml
This PR resolves #197 by replacing interiors.xml with the one provided by freeroam.
https://github.com/multitheftauto/mtasa-resources/blob/master/%5Bgameplay%5D/freeroam/data/interiors.xml
=> admin: Fix #197 badly placed interiors

[admin]/admin2/server/admin_server.lua
Add missing line change introducted in one of my recently commited (https://github.com/multitheftauto/mtasa-resources/commit/1b99a05b948abd74df5cea97b7f5b71ed0b22be9) - it was removed somehow
// cc @qaisjp
=> admin2: Fix Anonymous Admin not working

[admin]/acpanel/c_gui_ac.lua
This PR will add missing SD #36 to the acpanel interface.
=> Add SD #36 to acpanel UI

.gitignore, [admin]/admin/conf/reports.xml
.gitignore
+ ~~[admin]/admin/conf/IpToCountryCompact.csv~~
+ [admin]/admin/conf/reports.xml
File deletions
- [admin]/admin/conf/reports.xml
=> Add admin/conf files to .gitignore

[gamemodes]/[race]/[addons]/race_ghost/meta.xml, [gamemodes]/[race]/[addons]/race_ghost/playback_client.lua, [gamemodes]/[race]/race/editor_support_client.lua, [gamemodes]/[race]/race/meta.xml, [gamemodes]/[race]/race/modes/base.lua, [gamemodes]/[race]/race/race_client.lua, [gamemodes]/[race]/race/race_server.lua
https://wiki.multitheftauto.com/wiki/SetVehicleTurnVelocity
https://wiki.multitheftauto.com/wiki/GetVehicleTurnVelocity
=> race: fix deprecated functions

[gamemodes]/[race]/race/race_server.lua, [gamemodes]/[race]/race/racemap.lua
=> race: add the additional rotation attributes in spawnpoints

[editor]/editor_gui/client/browser/browserList.lua, [editor]/editor_gui/client/elementproperties.lua, [editor]/editor_main/client/controls.lua, [editor]/editor_main/client/main.lua, [editor]/editor_main/meta.xml
Closes #238 
To lock/unlock an element use the 'L' key
you still can select it from the elements browser
=> editor: add ability to lock elements

[gamemodes]/[race]/race/meta.xml, [gamemodes]/[race]/race/race_server.lua
=> race: end the map when only spectators are left

[web]/resourcemanager/manager.lua
=> resourcemanager: Fix start/load dates

[admin]/admin2/client/main/admin_resources.lua
=> admin2: add filter to resource's tab

[admin]/admin/client/gui/admin_main.lua, [admin]/admin2/client/main/admin_chat.lua
=> admin: Remove a blank line in the admin chat memo

[editor]/editor_main/server/mapsettingssync.lua
=> editor: reset availGamemodes table after creating a new map

[admin]/admin/server/admin_server.lua, [admin]/admin/server/admin_sync.lua
admin_server.lua: an end with no need.
admin_sync.lua: sometimes aPlayers table doesn't get the correct index in loop. Added isElement function to check.
=> admin: it updates admin_server.lua and admin_sync.lua

[gameplay]/headshot/headshot.lua
👋🏻
- Removed triggerEvent, in fact there's no need for it, since no other resource use it.
- Replaced getRootElement() with root predefined variable.
- Switched to non-anonymous functions.
=> headshot: minor improvements

[admin]/admin/server/admin_server.lua
It happens when a player has % after his nickname, the output message isn't complete.
That PR fixes it.
=> admin: fix output message on actions

[admin]/admin/client/gui/admin_main.lua, [admin]/admin/meta.xml, [admin]/admin/server/admin_server.lua
Added a command handler which triggers aAdminChat and made the command name a setting which can be changed.
=> Add admin chat command

[admin]/admin/server/admin_server.lua
=> Fixed bugs introduced by eef212e (admin: fix output message on actions)

[admin]/admin/server/admin_server.lua
=> Fix admin slap error #302

[editor]/editor_gui/client/buttonclicked.lua, [editor]/editor_gui/client/elementproperties.lua, [editor]/editor_main/client/main.lua, [editor]/move_cursor/move_cursor.lua, [editor]/move_freecam/move_freecam.lua, [editor]/move_keyboard/move_keyboard.lua
This PR fixes #298 by adding a checker when doubleclick on the icons, placed on left-bottom screen.
Before: https://streamable.com/mu1xwe
Now: https://streamable.com/0t53o7
=> editor: fix camera stuck when doubleclick on bottom icons

[gameplay]/freeroam/data/interiors.xml
According to fandom, its Didier Sachs.
https://gta.fandom.com/wiki/Didier_Sachs
=> Fix some typo in interiors.xml

[admin]/admin/client/gui/admin_main.lua
this PR fixes a warning message on client's console introduced by me in PR #315
=> admin: fix warning message

[editor]/editor_main/server/saveloadtest_server.lua
This error was caused by me and I only found out now, after someone asked for help on the discord support channel, sorry for the lack of attention and the stupid error.
It would be very important if someone verifies/merge this as soon as possible because this bug has been present in the master for a few days.
=> editor: fix error introduced in PR #319

[gameplay]/defaultstats/defaultstats.lua, [gameplay]/defaultstats/meta.xml
- Replaced loop.
- Disabled OOP.
=> defaultstats: small fixes

[gamemodes]/[ctf]/[maps]/ctf-hydrastrike/KWKHYDRASTRIKEDM.LUA, [gamemodes]/[ctf]/[maps]/ctf-hydrastrike/KWKHYDRASTRIKEDM2.LUA, [gamemodes]/[ctf]/ctf/ctf.lua, [gamemodes]/[ctf]/ctf/meta.xml
- Cleanup + refactor.
- Errors/warnings remove.
- For team selection including also the keys arrow up/down. For a more user friendly experience.
- Fixing a broken map script.
=> ctf: maintenance (fixes, cleanup & refactor)

[admin]/admin/server/admin_server.lua
[Discord discussion](https://discord.com/channels/801330706252038164/801519095064428614/939557451638923314) (MTA dev server)
Confirmed by @Dutchman101 that it's no longer needed.
=> admin: Remove redundant serial check

[editor]/editor_main/client/mapEditorScriptingExtension_c.lua, [editor]/editor_main/server/mapEditorScriptingExtension_s.lua
Makes use of onPlayerResourceStart in order to send data to client.
=> editor_main: Improve scripting extensions

[web]/ajax/ajax.js
=> ajax: add json detection

[editor]/editor_gui/client/options_action.lua, [editor]/editor_gui/client/options_backend.lua, [editor]/editor_gui/client/options_gui.lua, [editor]/editor_main/client/controls.lua, [editor]/freecam/freecam.lua
This allows you to change fov from MTA settings. Helps a lot of when playing on wide-screen or editing map.
=> freecam: Add support for changing field of view

[editor]/edf/edf.lua, [editor]/editor_main/client/main.lua, [editor]/editor_main/server/saveloadtest_server.lua
Reverts multitheftauto/mtasa-resources#394
=> Revert "editor_main: Fix various issues"

[gameplay]/scoreboard/dxscoreboard_rt.lua
This fixes unwanted performance regression in function aforementioned above.
=> scoreboard: Fix performance regression in getCursorScoreboardPosition

[admin]/admin2/client/widgets/admin_spectator.lua
admin2 : fixed spectator player action GUI buttons which were non-functional due to referring to global variable names from old admin.
=> admin2: fixed spectator player action buttons

[editor]/editor_main/server/saveloadtest_server.lua, [editor]/editor_main/server/util.lua
=> editor_main: Fix rotation not saving properly

[gameplay]/hedit/client/gui/languages/portuguese.lua, [gameplay]/hedit/meta.xml
This PR adds Portuguese translations to hedit
Credit: Translations done by [DDT]ForM and [G4]Blennk
=> hedit: add portuguese transalations

[admin]/admin/client/gui/admin_inputbox.lua, [editor]/editor_main/client/complex.lua, [editor]/editor_main/client/matrix.lua, [gameplay]/sirenEdit/complex.lua, [gameplay]/sirenEdit/matrix.lua, [managers]/votemanager/votemanager_server.lua
=> various: Remove loadstring from few places

[admin]/admin/conf/skins.xml
https://github.com/multitheftauto/mtasa-resources/pull/447
In version 1.6, I integrated the new skins added to the admin panel
=> Update "adminpanel" skins.xml

[gameplay]/hedit/client/gui/languages/turkish.lua
=> Update hedit's turkish language

[admin]/admin2/admin_definitions.lua, [admin]/admin2/client/main/admin_resources.lua, [admin]/admin2/server/admin_server.lua
Remove code execution functionality from `admin2`, just as it was removed in `admin` via #442
=> Remove code execution functionality from `admin2`

[admin]/admin2/client/main/admin_server.lua, [admin]/admin2/client/widgets/admin_server_conf.lua, [admin]/admin2/conf/ACL.xml, [admin]/admin2/meta.xml, [admin]/admin2/server/admin_functions.lua, [admin]/admin2/server/admin_server.lua
I think it will be useful to be able to configure the server from the admin panel (as much as the setServerConfigSetting function allows)
Such a proposal can be found in the project https://github.com/multitheftauto/mtasa-resources/projects/1
=> admin2: Ability to change server configuration settings

[gameplay]/internetradio/config/SRadioConfig.lua, [gameplay]/internetradio/handle_radio/SHandleRadio.lua
- If player is in vehicle, speaker should get attached to it
- Two configurable options:
-> Destroy attached speaker if vehicle explodes
-> Destroy attached speaker if vehicle gets destroyed
=> internetradio: add attaching to vehicles

[editor]/editor_gui/client/currentbrowser.lua
Fixes multitheftauto/mtasa-resources#525
=> fixes current elements window pop up

[gamemodes]/[race]/race/racevoting_server.lua
Fix typo in killer punchline chat message
=> race: Update racevoting_server.lua

[gamemodes]/[race]/race/modes/base.lua, [gameplay]/killmessages/scripts/client/c.ui.lua
=> Fix issue with killmessages not working in race

[editor]/edf/edf.lua
Fixes #639, i changed the model from dynamic to static in order to fix this issue
old model
new model
=> edf: Fix edf element falls or teleport when interacting with water/players

[editor]/move_freecam/move_freecam.lua
=> move_freecam: Fix element physics when interacting with water or other elements

[gameplay]/freeroam/data/interiors.xml
Winner winner, chicken dinner. Fixes #615
=> Fix positions of Diner 1 and Diner 2 interiors
